# **Lesson 1**

## Python list

In [ ]:
list1 = [1, 2, 3, 4, 5]
print(list1)
print(list1[0])
list2 = ["John", 41, list1, True]
print(list2)

[1, 2, 3, 4, 5]
1
['John', 41, [1, 2, 3, 4, 5], True]


## Numpy

In [ ]:
import numpy as np
np1 = np.array([0, 1, 2, 3, 4, 5])
print(np1)
print(np1.shape)

[0 1 2 3 4 5]
(6,)


### Create with range

In [ ]:
np2 = np.arange(10)
print(np2)
np3 = np.arange(0,10,2)  #start = 0, end = 9, step = 2
print(np3)


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]


### Zeros

In [ ]:
#One dimension
np4 = np.zeros(10)
print(np4)
#Multi dimension
np5 = np.zeros((2,10))    #2 dimensions, 10 elements each
print(np5)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Full

In [ ]:
#One dimension
np6 = np.full((10), 6)
print(np6)
#Multidimension
np7 = np.full((3,5), 5)    #2 dimension, 10 elements of 5 each
print(np7)

[6 6 6 6 6 6 6 6 6 6]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


### Convert list to numpy array

In [ ]:
mylist = [1, 2, 3, 4, 5]
np8 = np.array(mylist)
print(np8)

[1 2 3 4 5]


# Lesson 2: Slicing numpy array

In [ ]:
import numpy as np
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#return 2, 3, 4, 5
print(np1[1:5])

#return from something to the end
print(np1[3:])

#return negative slices
print(np1[-3:-1])

#steps
print(np1[1:5])
print(np1[1:5:2])

#steps on the entire array
print(np1[::2])


[2 3 4 5]
[4 5 6 7 8 9]
[7 8]
[2 3 4 5]
[2 4]
[1 3 5 7 9]


## Slicing 2D array

In [ ]:
#slide 2D array
np2 = np.array([[1, 2, 3, 4, 5],[6, 7,8 , 9, 10]])
print(np2[1][2])    #8
print(np2[1,2])   #also 8
print(np2[0:1, 1:3])
print(np2[0:2, 1:3])

8
8
[[2 3]]
[[2 3]
 [7 8]]


# Lesson 3: Universal Function

In [ ]:
import numpy as np
np1 = np.array([0,-1,2,-3,4,5,-6,7,8,9])
print(np1)

#Square root of each element:
#print(np.sqrt(np1))

#Absolute value of each element:
print(np.absolute(np1))

[ 0 -1  2 -3  4  5 -6  7  8  9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
#Exponential
print(np.exp(np1))

[1.00000000e+00 3.67879441e-01 7.38905610e+00 4.97870684e-02
 5.45981500e+01 1.48413159e+02 2.47875218e-03 1.09663316e+03
 2.98095799e+03 8.10308393e+03]


In [ ]:
#Min/Max
print(np.max(np1))
print(np.min(np1))

9
-6


In [ ]:
#Sign negative, positive
print(np.sign(np1))

[ 0 -1  1 -1  1  1 -1  1  1  1]


In [ ]:
#Trigonometric
print(np.sin(np1))

[ 0.         -0.84147098  0.90929743 -0.14112001 -0.7568025  -0.95892427
  0.2794155   0.6569866   0.98935825  0.41211849]


In [ ]:
#log
print(np.log(np1))

[      -inf        nan 0.69314718        nan 1.38629436 1.60943791
        nan 1.94591015 2.07944154 2.19722458]


<ipython-input-30-c8962eff5aff>:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(np1))
<ipython-input-30-c8962eff5aff>:2: RuntimeWarning: invalid value encountered in log
  print(np.log(np1))


#Lesson 4: Copy vs View

In [ ]:
import numpy as np
np1 = np.array([1, 2, 3, 4, 5])
#Create a view: when original change,
#view also change and reverse
np2 = np1.view()
print(f"Original np1 {np1}")
print(f"Original np2 {np2}")
np2[0] = 41
print(f"Change np1 {np1}")
print(f"original np2 {np2}")

Original np1 [1 2 3 4 5]
Original np2 [1 2 3 4 5]
Change np1 [41  2  3  4  5]
original np2 [41  2  3  4  5]


In [ ]:
#Create a copy: don't change
np1 = np.array([1, 2, 3, 4 ,5])
np2 = np1.copy()
print(f"Original np1 {np1}")
print(f"Original np2 {np2}")
np1[0] = 41
print(f"Change np1 {np1}")
print(f"Original np2 {np2}")

Original np1 [1 2 3 4 5]
Original np2 [1 2 3 4 5]
Change np1 [41  2  3  4  5]
Original np2 [1 2 3 4 5]


#Lesson 5: Shape and Reshape arrays

In [ ]:
#Create 1D numpy array and get shape
np1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print(np1)
print(np1.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
#Create 2D numpy array
np2 = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])
print(np2)
print(np2.shape)
#Reshape 2D
np3 = np1.reshape(2,6)
print(np3)
print(np3.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [ ]:
#Reshape 3D
np4 = np1.reshape(2,2,3)
print(np4)
print(np4.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [ ]:
#Flatten to 1D
np5 = np4.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


#Lesson 6: Iterating through numpy arrays

In [ ]:
import numpy as np
#1D
np1 = np.array([1, 2, 3, 4, 5, 6,7, 8, 9, 10])
for i in np1:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#2D
np2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8 ,9, 10]])
for i in np2:
  for x in i:
    print(x)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#3D array
np3 = np.array([[[1,2,3], [4, 5, 6]], [[7,8,9], [10,11,12]]])
for i in np3:
  for x in i:
    for z in x:
      print(z)

#Use np.nditer()
for x in np.nditer(np3):
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


#Lesson 7: Sorting numpy arrays

In [ ]:
import numpy as np
#np.sort()
np1 = np.array([6, 7, 4, 9, 0, 1])
print(np1)
print(np.sort(np1))


[6 7 4 9 0 1]
[0 1 4 6 7 9]


In [ ]:
#Alphabetical
np2 = np.array(["Jonh", "tina", "Aaron", "Zed"])
print(np2)
print(np.sort(np2))

['Jonh' 'tina' 'Aaron' 'Zed']
['Aaron' 'Jonh' 'Zed' 'tina']


In [ ]:
#Boolean
np3 = np.array([True, False, False, True])
print(np3)
print(np.sort(np3))

[ True False False  True]
[False False  True  True]


In [ ]:
#Return a copy not change a original
print(np1)
print(np.sort(np1))
print(np1)

[6 7 4 9 0 1]
[0 1 4 6 7 9]
[6 7 4 9 0 1]


In [ ]:
#2D array
np4 = np.array([[6,7,1,9],[8, 3, 5, 0]])
print(np4)
print(np.sort(np4))

[[6 7 1 9]
 [8 3 5 0]]
[[1 6 7 9]
 [0 3 5 8]]


#Lesson 8: Searching numpy array

In [ ]:
import numpy as np
#Search
np1 = np.array([1, 2, 3, 4, 5, 6, 7,8, 9, 10, 3])
x = np.where(np1==3)
print(np1)
print(x[0])
print(np1[x[0]])

[ 1  2  3  4  5  6  7  8  9 10  3]
[ 2 10]
[3 3]


In [ ]:
#Return even item
y = np.where(np1 % 2 ==0)
print(np1)
print(y[0])

[ 1  2  3  4  5  6  7  8  9 10  3]
[1 3 5 7 9]


#Lesson 9: Filter numpy array

In [ ]:
#Filter numpy arrys with boolean index lists
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True, True, False, False,False,False,False,False,False,False]
print(np1)
print(np1[x])

[ 1  2  3  4  5  6  7  8  9 10]
[1 2]


In [ ]:
filtered = []
for thing in np1:
  if thing >5:
    filtered.append(True)
  else:
    filtered.append(False)

print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False, False, False, False, False, True, True, True, True, True]
[ 6  7  8  9 10]


In [ ]:
#Short cut
filtered = np1 % 2==0
print(np1)
print(filtered)
print(np1[filtered])

[ 1  2  3  4  5  6  7  8  9 10]
[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]
